apiVersion: v1
kind: PersistentVolume
metadata:
  name: ecommerce-db-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/postgres_data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecommerce-dbv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi